---
type: object
properties:
  deploy:
    description: Deploy namespace
    type: object
    properties:
      terraform:
        description: Terraform namespace
        type: object
        properties:
          required_providers:
            description: Terraform required providers
            type: object
            propertyNames:
              type: string
              description: Provider name
            additionalProperties:
              type: object
              properties:
                source:
                  type: string
                  description: Provider source
                version:
                  type: string
                  description: Provider version
              required:
              - source
              - version
        required:
        - required_providers
    required:
    - terraform
  TF_VAR_DIGITALOCEAN_API_TOKEN:
    type: string
    description: Digitalocean API token
required:
- deploy
allOf:
- if:
    properties:
      deploy:
        properties:
          terraform:
            properties:
              required_providers:
                required:
                - digitalocean
            required:
            - required_providers
        required:
        - terraform
    required:
    - deploy
  then:
    required:
    - TF_VAR_DIGITALOCEAN_API_TOKEN
- if:
    properties:
      deploy:
        properties:
          terraform:
            properties:
              required_providers:
                required:
                - cloudflare
            required:
            - required_providers
        required:
        - terraform
    required:
    - deploy
  then:
    required:
    - TF_VAR_CLOUDFLARE_API_TOKEN
